In [2]:
import pandas as pd

In [6]:
curr_csv = pd.read_csv('./gallicanLemmas/50gallican.csv')

In [ ]:
lemmatized_verses = []
for file_num in range(50,2600,50):
    curr_csv = pd.read_csv('./septuagintLemmas/'+str(file_num)+'Septuagint.csv')
    for verse_num in range(1, max(curr_csv['LOCATION'])+1):
        curr_verse = curr_csv[curr_csv['LOCATION'] == verse_num]
        verse_string = ''
        for lemma in curr_verse['TITLE']:
            verse_string += lemma[8:]+' '

        lemmatized_verses.append(verse_string[:-1])

In [ ]:
lemmatized_verses = []
for file_num in range(50,2600,50):
    curr_csv = pd.read_csv('./gallicanLemmas/'+str(file_num)+'Gallican.csv')
    for verse_num in range(1, max(curr_csv['LOCATION'])+1):
        curr_verse = curr_csv[curr_csv['LOCATION'] == verse_num]
        verse_string = ''
        for lemma in curr_verse['TITLE']:
            verse_string += lemma[8:]+' '

        lemmatized_verses.append(verse_string[:-1])

In [144]:
lemmatized_verses = []
for file_num in range(50,2600,50):
    curr_csv = pd.read_csv('./hebrewLemmas/'+str(file_num)+'hebrew.csv')
    for verse_num in range(1, max(curr_csv['LOCATION'])+1):
        curr_verse = curr_csv[curr_csv['LOCATION'] == verse_num]
        verse_string = ''
        for lemma in curr_verse['TITLE']:
            verse_string += lemma[8:]+' '

        lemmatized_verses.append(verse_string[:-1])

In [55]:
lemmatized_verses

['beatus vir qui non abeo in consilium impius et in via peccatum non sisto in cathedra derido non sedeo',
 'sed in lex dominus voluntas is et in lex is meditor dies atque nox',
 'et sum tamquam lignum transplanto iuxta rivulus aqua quod fructus suus do in tempus suus et folis is non defluo et omnis quod facio prospero',
 'non sic impius sed tamquam pulva qui proicio ventus',
 'propterea non resurgo impius in iudicium neque peccator in congregatio iustus',
 'quoniam novo dominus via iustus et iter impius pereo',
 'quare turbo gens et tres meditor inanius',
 'consurgo rex terra et princeps tracto pariter adverdo dominus et adverdo christus is',
 'disrumpo vinculus is et proicio ab nos laqueus is',
 'habitator caelum rideo dominus subsanno is',
 'tunc loquor ad is in ira suus et in furor suus conturbo is',
 'ego autem orditus sum rex meus super sion mons sanctus suus adnuntio deus praeceptum',
 'dominus dico ad ego filius meus sum tu ego hodie gigno tu',
 'postulo ab ego et do tu gens hereditas tuus et possessio tuus terminus terra',
 'pasco is in virga ferreus ut vas figula contior is',
 'nunc ergo rex intellego erudio iudex terra',
 'servo dominus in timor et exsulto in tremus',
 'adoro pure ne forte irascor et pereo de via cum exardeo post paululus furor is beatus omnis qui spero in is',
 'canticus davida cum fugio ab facies abessalon filius sui',
 'dominus quare multiplico sum hoss meus multus consurgo advisceo ego',
 'multus dico anima meus non sum salus hic in deus semper',
 'tu autem dominus clipeus circa ego gloria meus et exalto caput meus',
 'vocus meus ad dominus clamo et exaudio ego de mons sanctus suus semper',
 'ego dormio et soporo sum evigilo quia dominus sustento ego',
 'non timeo milius populus qui circumdo ego',
 'surgo dominus salvus ego facio deus meus quia percusso omnis inimicus meus maxillus dens impius confrago',
 'dominus sum salus super populus tuus benedictio tuus semper',
 'victor in psalmus canticus davida',
 'invoco ego exaudo ego deus iustitia meus in tribulatio dilato ego misereor meus et exaudo oratio meus',
 'filius virus usqueqo inclitus meus ignominiose diligo vanitas quaero mendacium semper',
 'et cognosco quoniam mirabilis reddo dominus sanctus suus dominus exaudio cum clamavo ad is',
 'irascor et nolo pecco loquor in cor vester super cubilis vester et taceo semper',
 'sacrifico sacrificium iustitia et fidite in dominus',
 'multus dico quis ostendo nos bonum lego super nos lux vultus tuus dominus',
 'do laetitia in cor meus in tempus frumentum et vinum is multiplico sum',
 'in pax simul requisca et dormio quia tu dominus specialiter securus habito facio ego',
 'victor pro hereditas canticus davida',
 'verba meus audio dominus intellego murio meus',
 'rex meus et deus meus quia tu depredo',
 'dominus mane audio vocus meus mane praeparo ad tu et contemplor',
 'quoniam non sum deus volo iniquitas tu nec habito iuxta tu malignus',
 'non sto iniquis in conspectus oculus tuus odi omnis operor iniquitas',
 'peido loquor mendacium virus sanguis et dolos abominor dominus',
 'ego autem in multitudo misericordia tuus introibo in domus tuus adoro in templum sanctus tuus in timor tuus',
 'dominus do ego in iustitia tuus propter insidiator meus dirigo ante facies meus via tuus',
 'non sum enim in os is rego interior is insidia sepulch pateo guttur is lingua suus levifico',
 'condemno is deus decido ab consilium suus iuxta multitudo scelus is expello is quoniam provoco tu',
 'et laeto omnis qui spero in tu in perpetuus laudo et protero is et laeto in tu qui diligo nomen tuus',
 'quia tu benedicimus iustus dominus ut scutus placabilitas corono is',
 'victor in psalmus super octavus canticus davida',
 'dominus ne in furor tuus arguo ego neque in ira tuus corripio ego',
 'misereor meus dominus quoniam infirmus sum sanus ego dominus quoniam conturbo sum os meus',
 'et anima meus turbo sum valde et tu dominus usqueqo',
 'reverto dominus ero anima meus saluus ego propter misericordia tuus',
 'quoniam non sum in mors recordatio tuus in infernus quis confiteor tu',
 'laboro in gemitum meus nator facio totus nox lectulus meus lacrima meus stro meus rigo',
 'caligo prae amaritudo oculus meus consumo sum ab universus hostus meus',
 'recedo ab ego omnis qui operor iniquitas quia audio dominus vocus fletus meus',
 'audio dominus deprecatio meus dominus oratio meus suscipio',
 'confundo et confurbo vehementer omnis inimicus meus reverto et confundo subito',
 'pro ignoratio davida quod cecinio dominus super verbum aethio filius ieminus',
 'dominus deus meus in tu spero saluus ego ab omnis persequor ego et liber ego',
 'ne forte capio ut leo anima meus laceo et non sum qui eruo',
 'dominus deus meus si facio iste si sum iniquitas in manus meus',
 'si reddo retribuo ego malum et dimitto hoss meus vacuus',
 'persequor inimicus anima meus et adprehendo et conculco in terra vita meus et gloria meus in pulver conloco semper',
 'surgo dominus in furor tuus elevo indigno super hoss meus et consurgo ad ego iudicium quod mando',
 'et congregatio tribus circumdo tu et pro hic in altus reverto',
 'dominus iudico populus iudo ego dominus secundum iustitia meus et secundum simplicitas meus qui sum in ego',
 'consumo malum iniquus et confirmo iustitia probator cor et renus deus iustus',
 'clipeus meus in deus qui salvo rego cor',
 'deus iudex iustus et fortis comminor totus dies',
 'non converto gladius suus acuo arcus suus tetendo et para ille',
 'et in ipse praeparavo vasa mors sagittas suus ad conburo operor sum',
 'ecce parturio iniquitas et concipio dolor pario mendacium',
 'lacus aperio et effodio is et incido in interitus qui operor sum',
 'reverto dolor suus in caput is et super vertix is iniquitas suus descendo',
 'confiteor dominus secundum iustitia is et canto nomen dominus altus',
 'victor pro torcularis canticus davida',
 'dominus dominator noster quam grans sum nomen tuus in universus terra qui pono gloria tuus super caelum',
 'ex os infantius et lacto perficio laus propter adversarius meus ut quiesco inimicus et ultor',
 'video enim caelum tuus opus digitus tuus luna et stella qui fundo',
 'quis sum homo quoniam recordaris is vel filius homo quoniam visitas is',
 'minuo is paulus parue ab deus gloria et decor corono is',
 'do is potestas super opus manus tuus cunctus pono sub pes is',
 'ovis et armentum omnis insuper et animal ager',
 'avis caelum et pisces mas qui pertranseo semitas pons',
 'dominus dominator noster quam grans sum nomen tuus in universus terra',
 'victor pro mors filius canticus davida',
 'confiteor dominus in totus cor meus narro omnis mirabilis tuus',
 'laeto et gaudeo in tu conor nomen tuus altus',
 'cum cado inimicus meus retrorsus et corrumro et peiero ab facies tuus',
 'facio enim iudicium meus et causa meus sedeo super solium iudex iustitia',
 'increpuio gens pereo impius nomen is delibo in sempiternus et iugiter',
 'conpleo sum solitudo in finis et civitas subverto pereo memoria is cum ipse',
 'dominus autem in sempiternus sedeo stabilio ad iudico solium suus',
 'et ipse iudico orbis in iustitia iudico populus in aequitas',
 'et sum dominus elevatio opprimo elevatio oportuna in angustia',
 'et confideo in tu qui nosco nomen tuus quoniam non derelinquo quaero tu dominus',
 'canto dominus habitator sion adnuntio in populus commutatio is',
 'quoniam quaero sanguis is recordo sum nec obliuiscor sum clamor pauper',
 'misertus sum meus dominus vido adflictio meus ex inimicum meus qui exalto ego de porta mors',
 'ut naro omnis laus tuus in porta filia sion exsulto in salutaris tuus',
 'demergo sum gens in interitus qui facio in res quod abscondo capio sum pes is',
 'agnitus sum dominus iudicium facio in opus manus suus corrumpo impius sonitus sempiternus',
 'converto impius in infernus omnis gens qui obliuiscor sum deus',
 'quoniam non in aeternus oblivio sum pauper exspectatio pauper non pereo in perpetuus',
 'surgo dominus non conforto homo iudico gens ante facies tuus',
 'pono dominus terror is scio gens homo sui esse semper',
 'quare dominus sum ab longe dispicio in tempus angustia',
 'in superbia impius ardeo pauper capio in scelus qui cogito',
 'quia laudo impius desiderium anima suus et avarus adplaudo sui',
 'blasphemo dominus impius secundum altitudo furor sui non requiro nec sum deus in omnis cogitatio is',
 'parturio via is in omnis tempus longe sum iudicium tuus ab facies is omnis inimicus suus dispicio',
 'loquor in cor suus non movo in generatio et generatio sum sine malum',
 'maledictio os is plenus sum et dolum et avaritia sub lingua is dolor et iniquitas',
 'sedeo insidio iuxta vestibula in abscondo ut interficio innocens oculus is robustus tuus circumspicio',
 'insidio in abscondo quasi leo in cubilis insidio ut rapio pauper rapio pauper cum adtraho is ad res suus',
 'et confraho subicio et inruo vis suus valenter',
 'dico in cor suus obliuiscor sum deus abscondo facies suus non respicio in perpetuus',
 'surgo dominus deus lego manus tuus nolo obliviscor pauper',
 'quare blasphemo impius deus dico in cor suus quod non requiro',
 'video quia tu labor et furor respicio ut do in manus tuus tu relinquo fortis tuus pupillus tu sum facio adiutor',
 'contior brachium impius et malignus quaero impietas is et non invenio',
 'dominus rex saeculum et aeternitas pereo gens de terra is',
 'desiderium pauper audio dominus praeparo ut cor is audio auris tuus',
 'ut iudex pupillum et opprimo et nequaquam ultra superbio homo de terra',
 'victor davida in dominus spero quomodo dico anima meus transvolus in mons ut avus',
 'quia ecce impius tetendo arcus pono sagitta suus super nervum ut sagitto in abscondo rego cor',
 'quia lex dissipo sum iustus quis operor sum',
 'dominus in templum sanctus suus dominus in caelum thronus is oculus is video palpebra is probo filius homo',
 'dominus iustus probo impius autem et diligo iniquitas odi anima is',
 'pluo super peccator laqueus ignis et sulfur et spiritus tempesto pars calix is',
 'quoniam iustus dominus iustitia diligo rego video facio is',
 'victor pro octavus canticus davida',
 'saluus dominus quoniam deficio sanctus quoniam inminuo sum fidelis ab filius homo',
 'frustra loquor unusquisque proximus suus labius subdolus in cor et cor loquor sum',
 'disperdo dominus omnis labia dolosus lingua magniloquus',
 'qui dico lingua noster roboro labia noster nos sum quis dominus noster sum',
 'propter vastitas inopus et gemitum pauper nunc consurgo dico dominus pono in salutaris auxilium is',
 'eloquia dominus eloquia mundus argentum ignis probo separo ab terra conor septupleo',
 'tu dominus custodio is serva nos ab generatio hic in aeternus',
 'in circuitus impius ambulo cum exalto sum vilis filius homo',
 'victor canticus davida',
 'usqueqo dominus oblivisco meus penitus usqueqo abscondo facies tuus ab ego',
 'usqueqo pono consilium in anima meus dolor in cor meus per dies usqueqo exalto inimicus meus super ego',
 'converto exaudo ego dominus deus meus inlumen oculus meus ne umquam obdormia in mors',
 'nequor dico inimicus meus praevaleo advisceo is hoss meus exsulto cum motus sum',
 'ego autem in misericordia tuus confido exsulto cor meus in salutaris tuus canto dominus quia reddo ego',
 'victor davida dico stultus in cor suus non sum deus corrumpo sum et abominabilis facio sum studiose non sum qui facio bonum',
 'dominus de caelum prospiceo super filius homo ut video si sum intellego requiro deus',
 'omnis recedo simul conglutino sum non sum qui facio bonum non sum usque ad unus',
 'nonne cognosco omnis qui operor iniquitas qui devoro populus meus ut cibus panis dominus non invoco',
 'ibi timeo formido quoniam deus in generatio iustus sum',
 'consilium pauper confudo quoniam dominus spes is sum',
 'quis do de sion salus israhel quando reditto dominus captivitas populus sui exsulto iacob et laeto israhel',
 'canticus davida dominus quis peregrinor in tentorius tuus et quis habito in mons sanctus tuus',
 'qui ingredior sine macula et operor iustitia loquor veritas in cor suus',
 'qui non sum facilis in lingua suus neque facio amicus suus malum et obprobrium non sustineo super vicinus suus',
 'dispicio oculus is inpro timeo autem dominus glorifico iuro ut sui adfligo et non muto',
 'pecunia suus non do ad usura et munus adverdo innoxius non accipio qui facio hic non movo in aeternus',
 'humilis et simplex davida custodeo ego deus quoniam spero in tu',
 'dico deus dominus meus sum tu bene ego non sum sine tu',
 'sanctus qui in terra sum et magnificus omnis voluntas meus in is',
 'multiplico idolon is post tergum sequor non litabor libamen is de sanguis neque adiumo nomen is in labium meus',
 'dominus pars hereditas meus et calix meus tu possessor sors meus',
 'linea cado ego in pulcherrimus et hereditas speciosus meus sum',
 'benedico dominus qui do consilium ego insuper et noctus erudio ego renes meus',
 'propono in conspectus meus semper quia ab dexter meus sum ne commoveo',
 'propterea laeto sum cor meus et exsulto gloria meus et caro meus habitavo confidenter',
 'non enim derelinquo anima meus in infernus nec do sanctus tuus vido corruptio',
 'ostendo ego semita vita plenitudo laetitia ante vultus tuus decor in dexter tuus aeternus',
 'oratio davida audio deus iustus intendo deprecatio meus auris percipio oratio meus absque labium mendacium',
 'de vultus tuus iudicium meus prodeo oculus tuus video aequitas',
 'probo cor meus visito nox conflo ego et non invenio',
 'cogitatio meus transeo os meus in opus homo propter verbum labium tuus ego observo via latro',
 'sustentus gressus meus in callis tuus et non labeo vestigium meus',
 'ego invoco tu quia exaudio ego deus incleno auris tuus ego audio eloquium meus',
 'mirabilis facio misericordia tuus salvator spero ab resisto dexter tuus',
 'custodeo ego quasi pupilla intus in oculus in umbrum alarum tuus protego ego',
 'ab facies impius vasto ego inimicus meus anima meus circumdo',
 'adipus suus concludo et os loquor sum superbum',
 'incedo adverdo ego nunc circumdo ego oculus suus pono declino in terra',
 'similitudo is quasi leo desidero praeda et quasi catulus leo sedeo in abscondo',
 'surgo dominus praevenio facies is incurva is saluus anima meus ab impio qui sum gladus tuus',
 'ab vir manus tuus dominus qui morior sum in profundus qui pars in vita et qui de abscondo tuus repleo ventra qui satio filius et dimitto reliquia suus parvulus is',
 'ego in iustitia video facies tuus impleo cum evigilavero similitudo tuus',
 'victor servo dominus davida qui loquor sum dominus verba canticum hic in dies qui libero is dominus de manus omnis inimicus suus et de manus saul',
 'et aio diligo tu dominus fortitudo meus',
 'dominus petra meus et robur meus et salvator meus deus meus fortis meus spero in is scutus meus et cornus salus meus susceptor meus',
 'laudo invoco dominus et ab inimicum meus salvus sum',
 'circumdo ego funis mors et torro diabeo terruero ego',
 'funis inferus circumdo ego praevenio ego laques mors',
 'in tribulatio meus invoco dominus et ad deus meus clamo exaudio de templum suus vocus meus et clamor meus ante facies is venio in auris is',
 'commoueo sum et contremuo terra et fundamentum mons concutio sum et conquasso quoniam irascor sum',
 'ascendo fumus de furor is et ignis ex os is devoro carbo incensus sum ab is',
 'inclino caelum et descendo et caligus sub pes is',
 'et ascendo super cherus et volago super pinna vens',
 'pono tenebra latibulum suus in circuitus is tabernaculum is tenebrosus aqua in nuberus aether',
 'prae fulgor in conspectus is nubes transeo grando et carbo ignis',
 'et intono de caelum dominus et altus do vocus suus grando et carbo ignis',
 'et emitto sagittas suus et dissipo is fulgus multiplico et conturbavo ille',
 'et appareo effusio aqua et revelo sum fundamentum orbis ab increpatio tuus dominus ab inspiratio spiritus furor tuus',
 'mitto de altus et accipio ego extraho ego de aquus multus',
 'libero ego de inimicum meus possum et de hic qui oderor ego quoniam robustus ego sum',
 'praevenio ego in dies adflictio meus et facio sum dominus firmamentum meus',
 'et educo ego in latitudo libero ego quia placeo is',
 'retribuo ego dominus secundum iustitia meus et secundum munditia manus meus reddo ego',
 'quia custodico via dominus et non ego impie ab deus meus',
 'omnis enim iudicium is in conspectus meus et praeceptum is non amo ab ego',
 'et sum inmaculo cum is et custodico ego ab iniquitas meus',
 'et restituo dominus ego secundum iustitia meus et secundum munditia manus meus in conspectus oculus is',
 'cum sanctus sanctus sum cum virus innocens innocenter ago',
 'cum eligo elego sum et cum pervedo pervers',
 'quia tu populus pauper salvo et oculus excello humilio',
 'quia tu inlumino lucernus meus dominus deus meus inlustro tenebra meus',
 'in tu enim curro accingo et in deus meus transilio mus',
 'deus inmacilo via is eloquium dominus ignis examino scutus sum omnis spero in sui',
 'quis sum deus praeter dominus et quis fortis praeter deus noster',
 'deus qui accingo ego fortitudo et pono inmacelo via meus',
 'coaequo pes meus cervus et super excello statuo ego',
 'doceo manus meus ad proelium et conpono quasi arcus aereus brachia meus',
 'do ego clipeus salus tuus et dexter tuus conforto ego et mansuetudo tuus multiplico ego',
 'dilato gressus meus subo ego et non deficio talis meus',
 'persequor inimicus meus et adprehendo et non revertor donec consuma is',
 'caedo is et non possum surgo cado sub pes meus',
 'accingo ego fortitudo ad proelium incurvo resisto ego sub ego',
 'inimicus meus do ego dorsus et odio ego disperdido',
 'clamo et non sum qui salvo ad dominus et non exaudio is',
 'deleo is ut pulver ante facies vens ut lutum platea proicio is',
 'salvo ego ab contradictio populus possum ego in caput gens populus qui ignoro servio ego',
 'auditio auris oboedio ego filius alienus mentior ego',
 'filius alienus defluo et contraho in angustia suus',
 'vico dominus et benedico deus meus et exalto deus salus meus',
 'deus qui do vindico ego et congrego populus sub ego',
 'qui sergo ego ab inimicum meus et ab resisto ego eleo ego ab virus iniquus liber ego',
 'propterea confiteor tu in gens dominus et nomen tuus canto',
 'magnifico salus rex sui et facio misericordia christus suus davida et semen is usque in aeternus',
 'victor canticus davida',
 'caelum enarro gloria deus et opus manus is adnuntio firmamentum',
 'dies dies eructo verbum et nox noctus indico scientia',
 'non sum sermo et non sum verba qui non audio vox is',
 'in universus terra exivo sonus is et in finis orbis verba is solus pono tabernaculum in is',
 'et ipse quasi spondeo procedo de thalamus suus exsulto ut fortis ad curro via',
 'ab summitas caelum egredior is et cursus is usque ad summitas ille nec sum qui sui abscondo ab calor is',
 'lex dominus inmacilo converto anima testimonium dominus fidelis sapientia praesto parvulus',
 'praeceptum dominus rectus laetifico cor mando dominus lucidus inlumino oculus',
 'timor dominus mundus persevero in saeculum iudicium dominus verus iustifico in semet ipse',
 'desiderabilis super aurum et lapis pretiosus multus et dulcus super mel et favum redundo',
 'unde et servus tuus doceo is in custodio is fructus multus',
 'error quis intellego ab occulo mundus ego',
 'ab superbum quoque liber servus tuus si non sum dominor meus tunc inmaculo sum et mundo ab delinquo magnus',
 'sum placeo sermo oris meus meditatio cor meus in conspectus tuus dominus fortitudo meus et redemptor meus',
 'victor canticus davida',
 'exaudio tu dominus in dies tribulatio protego tu nomen deus iacob',
 'mitto tu auxilium de sanctus et de sion roboro tu',
 'memor sum omnis sacrificium tuus et holoco tuus pingui fio semper',
 'do tu secundum cor tuus et omnis voluntas tuus impleo',
 'laudo in salutaris tuus et in nomen deus noster duco chor impleo dominus omnis petitio tuus',
 'nunc scio quoniam salvo dominus christus suus exaudio is de caelum sanctus suus in fortitudo salus dexter suus',
 'hio in currus et hio in equa nos autem nomen dominus deus noster recordo',

In [36]:
lemmatized_verses_table = pd.read_csv('hebrew_lemmatized_verses.csv')

In [37]:
lemmatized_verses_table

,Unnamed: 0,Psalm,Verse,lemmatized_verse
0,0,1,1,אשרי איש אשר לא הלך עצה רשע דרך חטא לא עמד מוש...
1,1,1,2,כי אם תורה יהוה חפץ תורה חלם יום לילה
2,2,1,3,היי עץ שתול על פלג מים אשר פרי ניתן עת עלה לא ...
3,3,1,4,לא כן רשע כי אם חץ אשר תדפנו רוח
4,4,1,5,על כן לא יקמו רשע משפט חטא עדה צדיק
...,...,...,...,...
2522,2522,150,2,הללוהו גבור הללוהו רב גידל
2523,2523,150,3,הללוהו תקיעה שופר הללוהו נבל נבל
2524,2524,150,4,הללוהו בת מחול הילל מניין מרום
2525,2525,150,5,הילל בצלצלי שמע הילל בצלצלי תרועה
2526,2526,150,6,כל נשמה הילל יה אלה יה

In [40]:
final_lemmatized_verses = lemmatized_verses_table[['Psalm', 'Verse']].copy()

In [41]:
final_lemmatized_verses['hebrew_lemmas'] = lemmatized_verses_table['lemmatized_verse']

In [56]:
final_lemmatized_verses['hebrew_psalter_lemmas'] = lemmatized_verses

In [58]:
final_lemmatized_verses.to_csv('all_lemmatized_verses.csv')

In [114]:
final_lemmatized_verses

,Psalm,Verse,hebrew_lemmas,septuagint_lemmas,gallican_psalter_lemmas,hebrew_psalter_lemmas
0,1,1,אשרי איש אשר לא הלך עצה רשע דרך חטא לא עמד מוש...,μακαριος αἰνέρω οἰ οὐκέω επορεύω εἶμι βούλομαι...,beatus vir qui non abeo in consilium impius et...,beatus vir qui non abeo in consilium impius et...
1,1,2,כי אם תורה יהוה חפץ תורה חלם יום לילה,ἀλή ἠμί εἶμι τίω νομέω κύριος τῷς ἐθέλω αὐτάω ...,sed in lex dominus voluntas is et in lex is me...,sed in lex dominus voluntas is et in lex is me...
2,1,3,היי עץ שתול על פלג מים אשר פרי ניתן עת עלה לא ...,καίω ἵστημι οἰδα τῷς σύλω τῷς πεφύτω πάρειμι ὁ...,et sum tamquam lignum quod planto sum secus de...,et sum tamquam lignum transplanto iuxta rivulu...
3,1,4,לא כן רשע כי אם חץ אשר תדפנו רוח,οὐχόω ουτώς οἶδα αἰσβέω οὐχόω ουτώς ἀλή ἠμί οἰ...,non sic impius non sic sed tamquam pulva qui p...,non sic impius sed tamquam pulva qui proicio v...
4,1,5,על כן לא יקמו רשע משפט חטא עדה צדיק,δίω τίυμμι οὐκέω ανίστημι αἰσβέω εἶμι κρίνω οὐ...,ideo non resurgo impius in iudicium neque pecc...,propterea non resurgo impius in iudicium neque...
...,...,...,...,...,...,...
2522,150,2,הללוהו גבור הללוהו רב גידל,αἰνέω αυτον ἕπομαι ὁ δυνάστεια αὐτάω αἰνέω αυτ...,laudo is in virtus is laudo is secundum multit...,laudo is in fortitudo is laudo is iuxta multit...
2523,150,3,הללוהו תקיעה שופר הללוהו נבל נבל,αἰνέω αυτον εἶμι ηχω σαλπιγγος αἰνέω αυτον εἶμ...,laudo is in sonus tuba laudo is in psalterium ...,laudo is in clangor bucina laudo is in psalter...
2524,150,4,הללוהו בת מחול הילל מניין מרום,αἰνέω αυτον εἶμι τυμπανω καίω χορόω αἰνέω αυτο...,laudo is in tympanus et chor laudo is in cor e...,laudo is in tympanus et chor laudo is in cor e...
2525,150,5,הילל בצלצלי שמע הילל בצלצלי תרועה,αἰνέω αυτον εἶμι κυμβάλη ευηχής αἰνέω αυτον εἶ...,laudo is in cymbalis bene sono laudo is in cym...,laudo is in cymbalis sono laudo is in cymbalis...
2526,150,6,כל נשמה הילל יה אלה יה,πάσκω πέομαι αἰνέω τίνω κυριός αλληλουιος,omnis spiritus laudo dominus,omnis quod spiro laudo dominus